"""Export the O1-Sound checkpoint to C arrays for the FreeRTOS kernel.

Produces `freertos/generated/weights.h` (float32 weights + frontend tables)
consumed by `freertos/o1sound_kernel.c`. The C kernel is a reference
implementation that matches the PyTorch forward to ~1e-4 on logits; see
tests/test_c_parity.py for the host-side parity gate.

Usage:
    python scripts/export_c_kernel.py --ckpt checkpoints/o1sound.pt \
        --out freertos/generated/weights.h
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

import torch


def _fmt_array(name: str, t: torch.Tensor, per_line: int = 8) -> str:
    vals = t.detach().cpu().float().reshape(-1).tolist()
    lines = [f"static const float {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), per_line):
        chunk = []
        for v in vals[i:i + per_line]:
            s = f"{v:.9g}"
            if "." not in s and "e" not in s and "E" not in s:
                s += ".0"          # "0" -> "0.0", else C reads it as octal
            chunk.append(s + "f")
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", default="checkpoints/o1sound.pt")
    ap.add_argument("--out", default="freertos/generated/weights.h")
    ap.add_argument("--sample-rate", type=int, default=16000)
    ap.add_argument("--n-fft", type=int, default=480)
    ap.add_argument("--n-mels", type=int, default=40)
    ap.add_argument("--f-min", type=float, default=20.0)
    ap.add_argument("--f-max", type=float, default=7600.0)
    args = ap.parse_args()

    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    sd = ck["model"] if "model" in ck else ck["state_dict"]
    cfg = ck.get("config", {})
    hidden = int(cfg.get("hidden", 640))
    n_layers = int(cfg.get("n_layers", 2))
    n_classes = int(cfg.get("n_classes", 2))
    n_mels = args.n_mels

    # Frontend tables: hann window + Slaney mel filterbank, torch-identical.
    from o1sound.features import LogMel
    front = LogMel(args.sample_rate, args.n_fft, 160, n_mels, args.f_min, args.f_max)
    window = front.window.detach().cpu().float()
    fb = front.fb.detach().cpu().float()          # (n_mels, n_fft//2+1)
    n_freqs = args.n_fft // 2 + 1

    # LayerNorm eps (torch default).
    eps = 1e-5

    def linear(w: torch.Tensor, b: torch.Tensor | None):
        out = w.detach().cpu().float()
        return out, (b.detach().cpu().float() if b is not None else None)

    parts = [
        "// Auto-generated by scripts/export_c_kernel.py — do not edit.",
        f"// config: hidden={hidden} n_layers={n_layers} n_classes={n_classes}",
        f"//         n_mels={n_mels} n_fft={args.n_fft} sr={args.sample_rate}",
        "#pragma once",
        "#define O1S_HIDDEN " + str(hidden),
        "#define O1S_LAYERS " + str(n_layers),
        "#define O1S_CLASSES " + str(n_classes),
        "#define O1S_N_MELS " + str(n_mels),
        "#define O1S_N_FFT " + str(args.n_fft),
        "#define O1S_N_FREQS " + str(n_freqs),
        "#define O1S_EPS_LN " + f"{eps:.9g}f",
        "#define O1S_EPS_LOG 1e-6f",
        "",
        _fmt_array("o1s_window", window),
        "",
        _fmt_array("o1s_mel_fb", fb),
        "",
    ]

    norm_w = sd["norm.weight"]; norm_b = sd["norm.bias"]
    parts += [_fmt_array("o1s_norm_w", norm_w), "", _fmt_array("o1s_norm_b", norm_b), ""]

    for layer in range(n_layers):
        p = f"cells.{layer}"
        inp_w, inp_b = linear(sd[f"{p}.inp.weight"], sd[f"{p}.inp.bias"])
        rec_w, _ = linear(sd[f"{p}.rec.weight"], None)
        log_tau = sd[f"{p}.log_tau"].detach().cpu().float()
        # alpha = 1 / (softplus(log_tau) + tau_min); export alpha directly so
        # the C code does no transcendental work on the hot path.
        tau = torch.nn.functional.softplus(log_tau) + float(cfg.get("tau_min", 1.0))
        alpha = 1.0 / tau
        d_in = inp_w.shape[1]
        parts += [
            f"#define O1S_DIN_{layer} {d_in}",
            _fmt_array(f"o1s_l{layer}_inp_w", inp_w),
            "",
            _fmt_array(f"o1s_l{layer}_inp_b", inp_b),
            "",
            _fmt_array(f"o1s_l{layer}_rec_w", rec_w),
            "",
            _fmt_array(f"o1s_l{layer}_alpha", alpha),
            "",
        ]

    head_w, head_b = linear(sd["head.weight"], sd["head.bias"])
    parts += [_fmt_array("o1s_head_w", head_w), "", _fmt_array("o1s_head_b", head_b), ""]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts), encoding="utf-8")
    total = sum(t.numel() for t in sd.values())
    print(f"wrote {out}  ({total} params, {hidden}x{n_layers}, {n_classes} classes)")


if __name__ == "__main__":
    main()
